baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Hugo Profile"
theme: hugo-profile
publishDir: "./docs"

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:

    #Dropdown menu
    - identifier: dropdown
      title: Example dropdown menu
      name: Dropdown
      weight: 2
    - identifier: dropdown1
      title: example dropdown 1
      name: example 1
      url: /#
      parent: dropdown
      weight: 1
    - identifier: dropdown2
      title: example dropdown 2
      name: example 2
      url: /#
      parent: dropdown
      weight: 2

params:
  title: "Hugo Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Ruixin."
    subtitle: "I'm an operations researcher"
    content: "A passionate project manager and operations researcher. I tend to apply operations research algorithms and project managing expertise to help companies."
    image: /images/hero.svg
  
        -
      

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am a passionate project manager and operations researcher. I have a background in Industrial Engineering Operations research, and a degree from Engineering Management and I have a strong interest in boardgames and electronic games. I am currently finishing up my degree in Engineering Management and will be working for Dell after graduation. 

      I am currently working on a project that renovating a medical company's dashboard system.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "AMPL"
        - "Linear Programing"
        - "Integer Programing"
        - "Column Generation"
        - "Six Sigma"

  # Experience
  experience:
    enable: true
    items:
      - job: "A"
        company: "b"
        companyUrl: "https:a.com"
        date: "Jan 2022 - present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        content: "I am currently working as A for company B here in Madison."

      - job: "A"
        company: "c"
        companyUrl: "https://example.com"
        date: "Sep 2020 - Dec 2021"
        featuredLink:
          enable: true
          url: "https://example.com"
        info:
          enable: true
        content: "I worked as A for company C for about a year."
       
      - job: "D"
        company: "Z"
        companyUrl: "https://example.com"
        date: "Jan 2020 - Aug 2020"
        info:
          enable: false
        featuredLink:
          enable: true
          url: "https://example.com"
        content: I worked as a intern for company Z as a D for a short time, here I gained valuable expereice moving forward.
          


  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Master of Engineering Engineering Management"
        school:
          name: "Cornell University"
          url: "https://example.org"
        date: "2021 - 2022"
        GPA: "expected 3.8 out of 4"
        content: |-
          - Helped startup on Engineering economics.
          - Helped Health company on dashboard building
      - title: "Bachelor of Science in Industrial Engineering"
        school:
          name: "University of Wisconsin-Madison"
          url: "https://example.org"
        date: "2017 - 2021"
        GPA: "3.5 out of 4"
        content: |-
          Worked as a TA
          Worked on a paper for ergonomic furniture design
          Worked on operations research for 3 different companies 

       

 


  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: xxxx@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com